# Generated by Django 5.2.1 on 2025-05-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_image_remove_blog_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='summary',
        ),
    ]
